/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_U.h"
#include "PWM_OUT_U_aliases.h"
#include "PWM_OUT_U.h"
#include "PWM_OUT_W_aliases.h"
#include "PWM_OUT_W.h"
#include "PWM_W.h"
#include "PWM_V.h"
#include "Clock_PWM.h"
#include "ControlReg_PWM.h"
#include "PWM_OUT_V_aliases.h"
#include "PWM_OUT_V.h"
#include "CSN_1_aliases.h"
#include "CSN_1.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "UART_1.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "HFT_ISR.h"
#include "Clock_4kHz.h"
#include "GD_EN_aliases.h"
#include "GD_EN.h"
#include "AIN_1_aliases.h"
#include "AIN_1.h"
#include "CR_Leds.h"
#include "Pin_KitLed_aliases.h"
#include "Pin_KitLed.h"
#include "AIN_6_aliases.h"
#include "AIN_6.h"
#include "AIN_2_aliases.h"
#include "AIN_2.h"
#include "ADC_SAR_1.h"
#include "Status_Reg_Aux_ADC.h"
#include "ADC_SAR_Seq_1.h"
#include "AIN_7_aliases.h"
#include "AIN_7.h"
#include "AIN_5_aliases.h"
#include "AIN_5.h"
#include "AIN_4_aliases.h"
#include "AIN_4.h"
#include "AIN_0_aliases.h"
#include "AIN_0.h"
#include "AIN_3_aliases.h"
#include "AIN_3.h"
#include "Clock_1kHz.h"
#include "LFT_ISR.h"
#include "Timer_1.h"
#include "US_CLOCK.h"
#include "SPIM_1_IntClock.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

